[project]
name = "portfolio_sreejith"
version = "1.0.0"
description = "My portfolio website."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
